name: tommysor_test

on:
  push:
    branches: [ "tommysor/integrationTests" ]

jobs:
  IntegrationTests:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          ftpServer: pure-ftpd
        - os: ubuntu-latest
          ftpServer: vsftpd
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        FluentFTP__Tests__Integration__FtpServerKey: ${{ matrix.ftpServer }}
      run: dotnet test --no-build --verbosity normal
